[build]
  base = "."
  publish = "dist/backoffice/browser"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20.19.0"

# Disable all plugins
[build.processing]
  skip_processing = true

# SPA redirects for Angular
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
