controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Test route for debugging
test_users:
    path: /api/v1/test/users
    controller: App\Controller\Api\TestController::getUsers
    methods: [GET]
