[build]
  base = "."
  publish = "dist/backoffice/browser"
  command = "npm run build --prefix apps/backoffice"

[build.environment]
  NODE_VERSION = "18"

# Explicitly disable ALL Angular-related plugins
[[plugins]]
  package = "@netlify/angular-runtime"
  [plugins.inputs]
    enabled = false

# Force disable Angular detection
[build.processing]
  skip_processing = false

# SPA redirects for Angular
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "origin-when-cross-origin"

# Asset caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
