// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/products": {
    params: {};
  };
  "/products/:id": {
    params: {
      "id": string;
    };
  };
  "/coverage-calculator": {
    params: {};
  };
  "/orders": {
    params: {};
  };
  "/orders/:id": {
    params: {
      "id": string;
    };
  };
  "/shipping-calculator": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/products": {
    params: {};
  };
  "/admin/products/new": {
    params: {};
  };
  "/admin/products/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/admin/orders": {
    params: {};
  };
  "/admin/users": {
    params: {};
  };
  "/admin/suppliers": {
    params: {};
  };
  "/admin/suppliers/new": {
    params: {};
  };
  "/admin/suppliers/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/admin/reviews": {
    params: {};
  };
  "/api/verify": {
    params: {};
  };
  "/api/logout": {
    params: {};
  };
  "/api/register": {
    params: {};
  };
  "/api/product-detail/:id": {
    params: {
      "id": string;
    };
  };
  "/api/orders/:id": {
    params: {
      "id": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/dashboard" | "/products" | "/products/:id" | "/coverage-calculator" | "/orders" | "/orders/:id" | "/shipping-calculator" | "/login" | "/register" | "/profile" | "/admin" | "/admin/products" | "/admin/products/new" | "/admin/products/:id/edit" | "/admin/orders" | "/admin/users" | "/admin/suppliers" | "/admin/suppliers/new" | "/admin/suppliers/:id/edit" | "/admin/reviews" | "/api/verify" | "/api/logout" | "/api/register" | "/api/product-detail/:id" | "/api/orders/:id" | "/*";
  };
  "./routes/_layout.tsx": {
    id: "routes/_layout";
    page: "/" | "/dashboard" | "/products" | "/products/:id" | "/coverage-calculator" | "/orders" | "/orders/:id" | "/shipping-calculator" | "/login" | "/register" | "/profile" | "/admin" | "/admin/products" | "/admin/products/new" | "/admin/products/:id/edit" | "/admin/orders" | "/admin/users" | "/admin/suppliers" | "/admin/suppliers/new" | "/admin/suppliers/:id/edit" | "/admin/reviews";
  };
  "./features/home/pages/HomePage.tsx": {
    id: "features/home/pages/HomePage";
    page: "/";
  };
  "./features/dashboard/pages/DashboardPage.tsx": {
    id: "features/dashboard/pages/DashboardPage";
    page: "/dashboard";
  };
  "./routes/products.tsx": {
    id: "routes/products";
    page: "/products";
  };
  "./routes/products.$id.tsx": {
    id: "routes/products.$id";
    page: "/products/:id";
  };
  "./routes/coverage-calculator.tsx": {
    id: "routes/coverage-calculator";
    page: "/coverage-calculator";
  };
  "./routes/orders.tsx": {
    id: "routes/orders";
    page: "/orders";
  };
  "./routes/orders.$id.tsx": {
    id: "routes/orders.$id";
    page: "/orders/:id";
  };
  "./routes/shipping-calculator.tsx": {
    id: "routes/shipping-calculator";
    page: "/shipping-calculator";
  };
  "./routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "./routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "./routes/profile.tsx": {
    id: "routes/profile";
    page: "/profile";
  };
  "./routes/admin.tsx": {
    id: "routes/admin";
    page: "/admin";
  };
  "./routes/admin.products.tsx": {
    id: "routes/admin.products";
    page: "/admin/products";
  };
  "./routes/admin.products.new.tsx": {
    id: "routes/admin.products.new";
    page: "/admin/products/new";
  };
  "./routes/admin.products.$id.edit.tsx": {
    id: "routes/admin.products.$id.edit";
    page: "/admin/products/:id/edit";
  };
  "./routes/admin.orders.tsx": {
    id: "routes/admin.orders";
    page: "/admin/orders";
  };
  "./routes/admin.users.tsx": {
    id: "routes/admin.users";
    page: "/admin/users";
  };
  "./routes/admin.suppliers.tsx": {
    id: "routes/admin.suppliers";
    page: "/admin/suppliers";
  };
  "./routes/admin.suppliers.new.tsx": {
    id: "routes/admin.suppliers.new";
    page: "/admin/suppliers/new";
  };
  "./routes/admin.suppliers.$id.edit.tsx": {
    id: "routes/admin.suppliers.$id.edit";
    page: "/admin/suppliers/:id/edit";
  };
  "./routes/admin.reviews.tsx": {
    id: "routes/admin.reviews";
    page: "/admin/reviews";
  };
  "./features/auth/services/verify.server.ts": {
    id: "features/auth/services/verify.server";
    page: "/api/verify";
  };
  "./api/logout.server.ts": {
    id: "api/logout.server";
    page: "/api/logout";
  };
  "./api/register.server.ts": {
    id: "api/register.server";
    page: "/api/register";
  };
  "./api/product-detail.server.ts": {
    id: "api/product-detail.server";
    page: "/api/product-detail/:id";
  };
  "./api/orders.server.ts": {
    id: "api/orders.server";
    page: "/api/orders/:id";
  };
  "./routes/404.tsx": {
    id: "routes/404";
    page: "/*";
  };
};