nelmio_api_doc:
    areas:
        path_patterns:
            - ^/api(?!/doc)
    models:
        use_jms: false
    documentation:
        info:
            title: VNCompare API
            description: |
                Vietnam's premier paint comparison platform API.
                
                This API provides comprehensive functionality for:
                - User authentication and management
                - Product catalog and search
                - Order processing and tracking
                - Supplier management
                - Reviews and ratings
                - Address management (Vietnam-specific)
                - Analytics and reporting
                
                ## Authentication
                Most endpoints require JWT authentication. Include the token in the Authorization header:
                ```
                Authorization: Bearer <your_jwt_token>
                ```
                
                ## Response Format
                All responses follow a consistent format:
                - **Success**: `{"success": true, "data": {...}, "meta": {...}}`
                - **Error**: `{"success": false, "error": {...}, "meta": {...}}`
                
                ## Rate Limiting
                API requests are rate-limited to prevent abuse. Check response headers for current limits.
                
                ## Vietnam-Specific Features
                - Vietnamese phone number validation
                - Address structure (Province/District/Ward)
                - Local payment gateways (VNPay, MoMo, ZaloPay)
                - Paint coverage calculations in m²/liter
            version: 1.0.0
            contact:
                name: VNCompare API Support
                email: api-support@vncompare.com
                url: https://vncompare.com
            license:
                name: MIT
                url: https://opensource.org/licenses/MIT
        servers:
            - url: http://localhost:8000/api/v1
              description: Development server
            - url: https://api.vncompare.com/api/v1
              description: Production server
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
            schemas:
                Error:
                    type: object
                    properties:
                        success:
                            type: boolean
                            example: false
                        error:
                            type: object
                            properties:
                                code:
                                    type: string
                                    example: VALIDATION_ERROR
                                message:
                                    type: string
                                    example: Validation failed
                                details:
                                    type: array
                                    items:
                                        type: object
                                        properties:
                                            field:
                                                type: string
                                                example: email
                                            message:
                                                type: string
                                                example: This email is already registered
                        meta:
                            type: object
                            properties:
                                timestamp:
                                    type: string
                                    format: date-time
                                    example: 2024-01-01T00:00:00Z
                                requestId:
                                    type: string
                                    example: req_123456789
                Success:
                    type: object
                    properties:
                        success:
                            type: boolean
                            example: true
                        message:
                            type: string
                            example: Operation completed successfully
                        data:
                            type: object
                        meta:
                            type: object
                            properties:
                                timestamp:
                                    type: string
                                    format: date-time
                                    example: 2024-01-01T00:00:00Z
                                requestId:
                                    type: string
                                    example: req_123456789
        security:
            - Bearer: []
