headersOrigin = "config"
redirectsOrigin = "config"

[functions]

[functions."*"]

# Angular runtime plugin removed due to routing conflicts

[build]
publish = "/Users/thiennguyen/studyvn/apps/backoffice/dist/backoffice/browser"
publishOrigin = "config"
commandOrigin = "config"
base = "/Users/thiennguyen/studyvn/apps/backoffice"
command = "npm run build"

[build.environment]
NODE_VERSION = "18"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "SAMEORIGIN"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "origin-when-cross-origin"

[[headers]]
for = "/assets/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]